#pragma link off all globals;
#pragma link off all classes;
#pragma link off all functions;
#pragma link C++ nestedclasses;

#pragma link C++ class TClock+;
#pragma link C++ class TTAC+;
#pragma link C++ class TADC+;
#pragma link C++ class TTrace+;
#pragma link C++ class TDDASTime+;
#pragma link C++ class TPIN+;
#pragma link C++ class TDSSD+;
#pragma link C++ class TSSSD+;
#pragma link C++ class TPSPMT+;
#pragma link C++ class TPID+;
#pragma link C++ class TCorrelatorData+;
#pragma link C++ class TDDASDiagnostics+;
#pragma link C++ class TLaBr3+;
#pragma link C++ class TClover+;
#pragma link C++ class TSeGA+;
#pragma link C++ class TBetaDecayParams+;
#pragma link C++ class TROOTDataOut+;
